name: Deploy Productivity Tracker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test app
      run: |
        python -c "import streamlit; print('Streamlit version:', streamlit.__version__)"
        python -c "import supabase; print('Supabase client available')"
    
    - name: Deploy to Streamlit Cloud
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🚀 App is ready for Streamlit Cloud deployment!"
        echo "Go to https://share.streamlit.io/ to deploy manually"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: main"
        echo "Main file: app.py"
